import React, { useEffect, useMemo, useState } from 'react'
import { supabase } from './supabase.js'
import { LogIn, LogOut, Save, ShieldCheck, Settings, Menu, FileText, RefreshCw } from 'lucide-react'

const Field = ({ label, value, onChange, textarea=false }) => <label className="block space-y-2"><span className="text-xs font-bold uppercase tracking-[.14em] text-slate-500">{label}</span>{textarea ? <textarea value={value || ''} onChange={e=>onChange(e.target.value)} rows={4} className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:border-blue-500"/> : <input value={value || ''} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:border-blue-500"/>}</label>

function Login({ onReady }) {
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
  const submit=async(e)=>{e.preventDefault();setBusy(true);setError('');const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error){setError(error.message);setBusy(false);return}onReady(data.session);setBusy(false)}
  return <div className="min-h-screen bg-slate-950 grid place-items-center p-5"><div className="w-full max-w-md rounded-[28px] bg-white p-7 shadow-2xl"><div className="mb-7 flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-blue-700 text-white"><ShieldCheck size={22}/></div><div><div className="text-xs font-extrabold tracking-[.18em] text-blue-700">PMM CMS</div><h1 className="text-xl font-black text-slate-900">Admin Control Center</h1></div></div><p className="mb-6 text-sm leading-6 text-slate-500">Masuk dengan akun admin PMM. Area ini tidak menyediakan pendaftaran publik.</p><form onSubmit={submit} className="space-y-4"><Field label="Email" value={email} onChange={setEmail}/><label className="block space-y-2"><span className="text-xs font-bold uppercase tracking-[.14em] text-slate-500">Password</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} className="w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-blue-500"/></label>{error&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}<button disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-xl bg-blue-700 px-4 py-3 font-bold text-white hover:bg-blue-800 disabled:opacity-60"><LogIn size={17}/>{busy?'Memeriksa...':'Masuk Admin'}</button></form><a href="/" className="mt-5 block text-center text-sm font-semibold text-slate-500 hover:text-blue-700">← Kembali ke website</a></div></div>
}

export default function AdminApp(){
 const [session,setSession]=useState(null),[authorized,setAuthorized]=useState(false),[loading,setLoading]=useState(true),[settings,setSettings]=useState({}),[nav,setNav]=useState([]),[blocks,setBlocks]=useState([]),[status,setStatus]=useState('')
 const load=async(s)=>{setLoading(true);const uid=s?.user?.id;if(!uid){setAuthorized(false);setLoading(false);return}const {data:admin}=await supabase.from('admin_users').select('role').eq('user_id',uid).maybeSingle();if(!admin){await supabase.auth.signOut();setAuthorized(false);setLoading(false);return}setAuthorized(true);const [{data:st},{data:n},{data:b}]=await Promise.all([supabase.from('site_settings').select('*').eq('id','main').single(),supabase.from('navigation_items').select('*').order('position'),supabase.from('content_blocks').select('*').order('key')]);setSettings(st?.config||{});setNav(n||[]);setBlocks(b||[]);setLoading(false)}
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);load(data.session)});const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(!s){setAuthorized(false);setLoading(false)}});return()=>l.subscription.unsubscribe()},[])
 const saveSettings=async()=>{setStatus('Menyimpan...');const {error}=await supabase.from('site_settings').update({config:settings,updated_by:session.user.id,updated_at:new Date().toISOString()}).eq('id','main');setStatus(error?error.message:'Pengaturan tersimpan ✓')}
 const saveNav=async()=>{setStatus('Menyimpan menu...');for(const item of nav){const {error}=await supabase.from('navigation_items').update({label:item.label,route:item.route,position:Number(item.position),visible:item.visible,updated_at:new Date().toISOString()}).eq('id',item.id);if(error){setStatus(error.message);return}}setStatus('Menu tersimpan ✓')}
 const saveBlock=async(block)=>{setStatus('Menyimpan konten...');const {error}=await supabase.from('content_blocks').update({title:block.title,body:block.body,image_url:block.image_url,enabled:block.enabled,updated_by:session.user.id,updated_at:new Date().toISOString()}).eq('key',block.key);setStatus(error?error.message:'Konten tersimpan ✓')}
 if(loading)return <div className="min-h-screen grid place-items-center bg-slate-950 text-white"><RefreshCw className="animate-spin"/></div>
 if(!session||!authorized)return <Login onReady={s=>{setSession(s);load(s)}}/>
 return <div className="min-h-screen bg-slate-100 text-slate-900"><header className="sticky top-0 z-20 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><div><div className="text-xs font-extrabold tracking-[.16em] text-blue-700">PMM ADMIN</div><div className="font-black">Content Control Center</div></div><div className="flex items-center gap-3"><span className="hidden text-xs text-slate-500 sm:block">{session.user.email}</span><button onClick={()=>supabase.auth.signOut()} className="flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-bold"><LogOut size={16}/>Keluar</button></div></div></header><main className="mx-auto max-w-6xl space-y-6 px-5 py-8">{status&&<div className="sticky top-20 z-10 rounded-xl border border-blue-100 bg-blue-50 px-4 py-3 text-sm font-semibold text-blue-800">{status}</div>}
 <section className="rounded-[24px] bg-white p-6 shadow-sm"><div className="mb-5 flex items-center gap-2"><Settings size={19} className="text-blue-700"/><h2 className="font-black">Identitas & Footer</h2></div><div className="grid gap-4 md:grid-cols-2"><Field label="Nama Brand" value={settings.brandName} onChange={v=>setSettings({...settings,brandName:v})}/><Field label="Perusahaan" value={settings.company} onChange={v=>setSettings({...settings,company:v})}/><Field label="WhatsApp" value={settings.whatsapp} onChange={v=>setSettings({...settings,whatsapp:v})}/><Field label="Email" value={settings.email} onChange={v=>setSettings({...settings,email:v})}/><Field label="Alamat" value={settings.address} onChange={v=>setSettings({...settings,address:v})}/><Field label="NIB" value={settings.nib} onChange={v=>setSettings({...settings,nib:v})}/><div className="md:col-span-2"><Field textarea label="Tentang PMM (singkat)" value={settings.about} onChange={v=>setSettings({...settings,about:v})}/></div></div><button onClick={saveSettings} className="mt-5 flex items-center gap-2 rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-bold text-white"><Save size={16}/>Simpan Pengaturan</button></section>
 <section className="rounded-[24px] bg-white p-6 shadow-sm"><div className="mb-5 flex items-center gap-2"><Menu size={19} className="text-blue-700"/><h2 className="font-black">Menu Website</h2></div><div className="space-y-3">{nav.map((x,i)=><div key={x.id} className="grid items-center gap-3 rounded-xl border border-slate-100 bg-slate-50 p-3 sm:grid-cols-[1.3fr_1fr_80px_90px]"><input value={x.label} onChange={e=>setNav(nav.map((n,j)=>j===i?{...n,label:e.target.value}:n))} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm"/><input value={x.route} onChange={e=>setNav(nav.map((n,j)=>j===i?{...n,route:e.target.value}:n))} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm"/><input type="number" value={x.position} onChange={e=>setNav(nav.map((n,j)=>j===i?{...n,position:e.target.value}:n))} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm"/><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={x.visible} onChange={e=>setNav(nav.map((n,j)=>j===i?{...n,visible:e.target.checked}:n))}/>Tampil</label></div>)}</div><button onClick={saveNav} className="mt-5 flex items-center gap-2 rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-bold text-white"><Save size={16}/>Simpan Menu</button></section>
 <section className="rounded-[24px] bg-white p-6 shadow-sm"><div className="mb-5 flex items-center gap-2"><FileText size={19} className="text-blue-700"/><h2 className="font-black">Konten Penting</h2></div><div className="grid gap-4 lg:grid-cols-2">{blocks.map((b,i)=><article key={b.key} className="rounded-2xl border border-slate-200 p-4"><div className="mb-4 flex items-center justify-between"><code className="text-xs font-bold text-blue-700">{b.key}</code><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={b.enabled} onChange={e=>setBlocks(blocks.map((x,j)=>j===i?{...x,enabled:e.target.checked}:x))}/>Aktif</label></div><div className="space-y-3"><Field label="Judul" value={b.title} onChange={v=>setBlocks(blocks.map((x,j)=>j===i?{...x,title:v}:x))}/><Field textarea label="Isi" value={b.body} onChange={v=>setBlocks(blocks.map((x,j)=>j===i?{...x,body:v}:x))}/><Field label="URL / path gambar" value={b.image_url} onChange={v=>setBlocks(blocks.map((x,j)=>j===i?{...x,image_url:v}:x))}/></div><button onClick={()=>saveBlock(blocks[i])} className="mt-4 flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2 text-xs font-bold text-white"><Save size={14}/>Simpan Blok</button></article>)}</div></section>
 </main></div>
}
